### ISSUE TITLE
rename default slave labels

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/qps-infra#165]
JENKINS_SLAVE_LABELS=qps-slave api web qa docker
to
JENKINS_SLAVE_LABELS=maven api web docker

i.e. we removed qps-slave and qa but added maven by default

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/qps-infra/commit/48f35dccd916358c94e6a127055615f38c8aa0e0
need get latest change from qps-infra, clear and start:
cd qps-infra
git checkout develo
git pull
./clear.sh
./start.sh

default jenkins-slave should have updated labels
![image](https://user-images.githubusercontent.com/4551455/81413519-3facfe80-914e-11ea-90d1-365a5ff0b752.png)

**Comment by okamara** [comment]
I still see old slave name
<img width="445" alt="Screen Shot 2020-05-08 at 8 07 04 PM" src="https://user-images.githubusercontent.com/32964663/81430085-865b2280-9167-11ea-8bf3-69b6fa27c0c1.png">

**Comment by vdelendik** [comment]
if no luck with pull just remove and re-clone from scratch:)

**Comment by dhreben** [comment]
Verified <img width="875" alt="Screen Shot 2020-05-08 at 21 27 24" src="https://user-images.githubusercontent.com/50950954/81437379-bf00f900-9173-11ea-860b-5909e037acc8.png">
